name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2.5.0
      name: Build the Docker image
      with:
        arch: aarch64
        distro: ubuntu18.04
        run: docker build src/docker --file src/docker/Dockerfile --tag unifi-docker-rpi4:$(date +%s)
